# Generated by Django 3.1.7 on 2021-02-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210218_1049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PI',
            new_name='PersonalInformation',
        ),
    ]
